language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - vincenthcui@qq.com
    on_success: change
    on_failure: always

install:
  - apt-get install jq
  - npm install -g gitbook-cli
  - npm install
  - gitbook install

script:
  - gitbook build

branches:
  only:
    - main

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  fqdn: rfb.vincentcui.cn
  on:
    branch: main