language: node_js
node_js:
  - "10"
cache: npm

notifications:
  pushover:
    api_key: "$PUSHOVER_KEY"
    users:
      - "$PUSHOVER_USER"
    on_success: change
    on_failure: always

install:
  - sudo apt-get install jq
  - npm install -g gitbook-cli
  - npm install
  - gitbook install

script:
  - cat <<< $(jq --arg secret "$GITTALK_SECRET" '.pluginsConfig.gittalk.clientSecret = $secret' book.json) > book.json
  - gitbook build

branches:
  only:
    - main

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  fqdn: rfb.vincentcui.cn
  on:
    branch: main